### PR TITLE
Support different keys for decryption and signature verification.

### PR DESCRIPTION
**Pull request by deskoh**
Client can only be configured to use the same private key (i.e. `key.pem`) for signature verification and assertion decryption.

This PR allows different keys to be configured.

### CODE REVIEW

**Comment by LoneRifle** [comment]
Under what circumstances is there a need to support different keys? From what I understand, spcp setups typically recycle the decrypt assertion key for signing. Also.. is there a way to make this change without breaking backward compatibility?

**Comment by deskoh** [comment]
Correct me if I'm wrong, my understanding is that the keys (or more specifically the X.509 certs) used by SPCP for signing and encryption are provided by the service provider, both of which could be different?

**Comment by LoneRifle** [comment]
Your understanding is correct - that said, I feel the need to retain backward compatibility so that those who have opted to use the same certs can continue to specify it as `appKey` in settings, perhaps as a fallback for `this.appSigningKey` and `this.appEncryptionKey`, ie, in the ctor,

```js
this.appSigningKey = config.appSigningKey || config.appKey
this.appEncryptionKey = config.appEncryptionKey || config.appKey
```

**Comment by deskoh** [comment]
Good suggestion and valid point.

To simplify usage, I added optional `appEncryptionKey` to be provided if it is different from `appKey` is used. This will avoid the need to deal with up to 3 'keys' parameters in the config, (Furthermore, the appKey is also used for JWT signing, which will make the usage even more complicated).

Aside, is it desirable to create a TypeScript definition? Included some jsdoc type error fixes in this PR as well.

**Comment by LoneRifle** [comment]
I would if I could. Happy to take a separate PR for that

**Pull request merged**
